export type CreationMediaRole = "COVER" | "VIDEO_POSTER" | "AUDIO" | "VIDEO";

export const CREATION_IMAGE_MAXIMUM_BYTES = 10 * 1024 * 1024;
export const CREATION_AUDIO_MAXIMUM_BYTES = 80 * 1024 * 1024;
export const CREATION_VIDEO_MAXIMUM_BYTES = 200 * 1024 * 1024;

export const CREATION_MEDIA_DELETION_CONFIRMATION = "CONFIRM_CREATION_MEDIA_DELETION";
